# Generated by Django 6.0.5 on 2026-05-13 01:34

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=160, verbose_name='jogo')),
                ('market', models.CharField(max_length=120, verbose_name='mercado')),
                ('odds', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='odd')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor apostado')),
                ('exchange_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='comissao da exchange (%)')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('won', 'Ganha'), ('lost', 'Perdida')], default='open', max_length=8, verbose_name='resultado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'aposta',
                'verbose_name_plural': 'apostas',
                'ordering': ['-created_at'],
            },
        ),
    ]
