# Generated by Django 6.0.5 on 2026-05-13 01:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('bookmaker', models.CharField(blank=True, max_length=80, verbose_name='casa/exchange')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo inicial')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'banca',
                'verbose_name_plural': 'bancas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='bankroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='dashboard.bankroll', verbose_name='banca'),
        ),
    ]
