# Generated by Django 6.0.5 on 2026-05-13 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bankroll_bet_bankroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankrollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposito'), ('withdraw', 'Saque'), ('adjustment', 'Ajuste'), ('transfer_in', 'Transferencia entrada'), ('transfer_out', 'Transferencia saida')], max_length=16, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='observacao')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.bankroll', verbose_name='banca')),
            ],
            options={
                'verbose_name': 'movimentacao',
                'verbose_name_plural': 'movimentacoes',
                'ordering': ['-created_at'],
            },
        ),
    ]
