# Generated by Django 6.0.5 on 2026-05-14 01:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bankrolltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankroll',
            name='daily_stop_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='stop loss diario (%)'),
        ),
        migrations.AddField(
            model_name='bankroll',
            name='daily_stop_win_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='stop win diario (%)'),
        ),
        migrations.AddField(
            model_name='bankroll',
            name='max_stake_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='stake maxima (%)'),
        ),
        migrations.AddField(
            model_name='bankroll',
            name='monthly_stop_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='stop loss mensal (%)'),
        ),
        migrations.AddField(
            model_name='bankroll',
            name='unit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='unidade padrao (%)'),
        ),
        migrations.AddField(
            model_name='bankroll',
            name='weekly_stop_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='stop loss semanal (%)'),
        ),
    ]
