# Generated by Django 6.0.5 on 2026-05-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bankroll_daily_stop_loss_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='competition',
            field=models.CharField(blank=True, max_length=120, verbose_name='competicao'),
        ),
        migrations.AddField(
            model_name='bet',
            name='entry_type',
            field=models.CharField(choices=[('pre_match', 'Pre-live'), ('live', 'Ao vivo')], default='pre_match', max_length=12, verbose_name='tipo de entrada'),
        ),
        migrations.AddField(
            model_name='bet',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data do evento'),
        ),
        migrations.AddField(
            model_name='bet',
            name='exact_score',
            field=models.CharField(blank=True, max_length=40, verbose_name='resultado exato'),
        ),
        migrations.AddField(
            model_name='bet',
            name='game_link',
            field=models.URLField(blank=True, verbose_name='link do jogo'),
        ),
        migrations.AddField(
            model_name='bet',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observacoes'),
        ),
        migrations.AddField(
            model_name='bet',
            name='sport',
            field=models.CharField(blank=True, default='Futebol', max_length=60, verbose_name='esporte'),
        ),
        migrations.AddField(
            model_name='bet',
            name='strategy',
            field=models.CharField(blank=True, max_length=120, verbose_name='estrategia/tipster'),
        ),
    ]
