# Generated by Django 6.0.5 on 2026-05-14 01:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_bet_competition_bet_entry_type_bet_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='mes de referencia')),
                ('profit_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='meta de lucro')),
                ('roi_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='meta de ROI (%)')),
                ('volume_target', models.PositiveIntegerField(default=0, verbose_name='meta de volume')),
                ('max_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='limite de perda')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
                ('bankroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='dashboard.bankroll', verbose_name='banca')),
            ],
            options={
                'verbose_name': 'meta mensal',
                'verbose_name_plural': 'metas mensais',
                'ordering': ['-month', 'bankroll__name'],
                'unique_together': {('bankroll', 'month')},
            },
        ),
    ]
