# Generated by Django 6.0.5 on 2026-05-16 03:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_bankroll_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=80, verbose_name='casa de aposta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilizada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
                ('source_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_freebets', to='dashboard.bet', verbose_name='aposta de origem')),
            ],
            options={
                'verbose_name': 'freebet',
                'verbose_name_plural': 'freebets',
                'ordering': ['-created_at'],
            },
        ),
    ]
