# Generated by Django 5.2.14 on 2026-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_bet_entity_alter_bankroll_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='away_team',
            field=models.CharField(blank=True, max_length=120, verbose_name='visitante'),
        ),
        migrations.AddField(
            model_name='bet',
            name='external_event_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='id externo do evento'),
        ),
        migrations.AddField(
            model_name='bet',
            name='external_sport_key',
            field=models.CharField(blank=True, max_length=80, verbose_name='sport key externo'),
        ),
        migrations.AddField(
            model_name='bet',
            name='home_team',
            field=models.CharField(blank=True, max_length=120, verbose_name='mandante'),
        ),
    ]
