# Generated by Django 5.2.14 on 2026-05-22 16:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_surebetentry_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankrolltransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'movimentação', 'verbose_name_plural': 'movimentações'},
        ),
        migrations.AlterField(
            model_name='bankroll',
            name='daily_stop_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='stop loss diário (%)'),
        ),
        migrations.AlterField(
            model_name='bankroll',
            name='daily_stop_win_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='stop win diário (%)'),
        ),
        migrations.AlterField(
            model_name='bankroll',
            name='max_stake_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='stake máxima (%)'),
        ),
        migrations.AlterField(
            model_name='bankroll',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankrolls', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='bankroll',
            name='unit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='unidade padrão (%)'),
        ),
        migrations.AlterField(
            model_name='bankrolltransaction',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Deposito'), ('withdraw', 'Saque'), ('adjustment', 'Ajuste'), ('transfer_in', 'Transferência entrada'), ('transfer_out', 'Transferência saida')], max_length=16, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='bankrolltransaction',
            name='note',
            field=models.CharField(blank=True, max_length=160, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='actual_net_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='resultado líquido real'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='competition',
            field=models.CharField(blank=True, max_length=120, verbose_name='competição'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='exchange_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='comissão da exchange (%)'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='strategy',
            field=models.CharField(blank=True, max_length=120, verbose_name='estratégia/tipster'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='notes',
            field=models.CharField(blank=True, max_length=160, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='month',
            field=models.DateField(verbose_name='mês de referência'),
        ),
        migrations.AlterField(
            model_name='surebetentry',
            name='cashback_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='cashback no cenário'),
        ),
        migrations.AlterField(
            model_name='surebetentry',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='comissão (%)'),
        ),
        migrations.AlterField(
            model_name='surebetentry',
            name='net_result',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='resultado líquido'),
        ),
        migrations.AlterField(
            model_name='surebetentry',
            name='notes',
            field=models.CharField(blank=True, max_length=180, verbose_name='observação'),
        ),
    ]
