# Generated by Django 5.2.14 on 2026-05-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_regulated_bookmakers_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='source_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome da fonte'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='source_type',
            field=models.CharField(choices=[('official', 'Site oficial'), ('affiliate', 'Agregador/afiliado'), ('manual', 'Manual')], default='official', max_length=16, verbose_name='tipo de fonte'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='validation_status',
            field=models.CharField(choices=[('confirmed_official', 'Confirmada no site oficial'), ('found_affiliate', 'Encontrada em afiliado'), ('pending_validation', 'Pendente de validação'), ('expired', 'Expirada')], default='confirmed_official', max_length=24, verbose_name='status de validação'),
        ),
    ]
