# Generated by Django 5.2.14 on 2026-05-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_promotion_source_name_promotion_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expira em'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='rule_summary',
            field=models.CharField(blank=True, max_length=220, verbose_name='resumo da regra'),
        ),
    ]
