# Generated by Django 5.2.14 on 2026-05-26 03:58

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_promotion_expires_at_promotion_rule_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmakeralias',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promotionpage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regulatedbookmaker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BookmakerEventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=120, verbose_name='id externo do evento')),
                ('bookmaker', models.CharField(max_length=80, verbose_name='casa')),
                ('home_team', models.CharField(max_length=120, verbose_name='mandante')),
                ('away_team', models.CharField(max_length=120, verbose_name='visitante')),
                ('event_url', models.URLField(blank=True, max_length=1000, verbose_name='URL do evento')),
                ('matched_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='confiança do match')),
                ('status', models.CharField(choices=[('found', 'Encontrado'), ('not_found', 'Não encontrado'), ('error', 'Erro'), ('stale', 'Desatualizado')], default='not_found', max_length=40, verbose_name='status')),
                ('last_error', models.CharField(blank=True, max_length=220, verbose_name='último erro')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='última verificação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'link de evento por casa',
                'verbose_name_plural': 'links de eventos por casa',
                'ordering': ['bookmaker', '-last_checked_at'],
                'unique_together': {('external_event_id', 'bookmaker')},
            },
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=120, verbose_name='id externo do evento')),
                ('bookmaker', models.CharField(max_length=80, verbose_name='casa')),
                ('market', models.CharField(max_length=80, verbose_name='mercado')),
                ('selection', models.CharField(max_length=120, verbose_name='seleção')),
                ('odd', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='odd')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL fonte')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='capturada em')),
            ],
            options={
                'verbose_name': 'snapshot de odd',
                'verbose_name_plural': 'snapshots de odds',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['external_event_id', 'market', '-captured_at'], name='dashboard_o_externa_8ee1d3_idx'), models.Index(fields=['bookmaker', '-captured_at'], name='dashboard_o_bookmak_63075a_idx')],
            },
        ),
    ]
