# Generated by Django 5.2.14 on 2026-05-31 03:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_manual_freebet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrolltransaction',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankroll_transactions', to='dashboard.bet', verbose_name='aposta'),
        ),
        migrations.AddField(
            model_name='surebetentry',
            name='bankroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surebet_entries', to='dashboard.bankroll', verbose_name='banca'),
        ),
        migrations.AddField(
            model_name='surebetentry',
            name='is_freebet_source',
            field=models.BooleanField(default=False, verbose_name='entrada da freebet usada'),
        ),
        migrations.AddField(
            model_name='surebetentry',
            name='liability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='responsabilidade'),
        ),
        migrations.AddField(
            model_name='surebetentry',
            name='mode',
            field=models.CharField(choices=[('back', 'Back'), ('lay', 'Lay')], default='back', max_length=4, verbose_name='modo'),
        ),
    ]
