# Generated by Django 5.2.14 on 2026-05-31 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_useraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='apelido')),
                ('bank_name', models.CharField(max_length=100, verbose_name='banco/instituição')),
                ('account_type', models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('payment', 'Conta de pagamento'), ('pix', 'Pix'), ('other', 'Outra')], default='checking', max_length=16, verbose_name='tipo')),
                ('agency', models.CharField(blank=True, max_length=20, verbose_name='agência')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='conta')),
                ('pix_key', models.CharField(blank=True, max_length=120, verbose_name='chave Pix')),
                ('notes', models.CharField(blank=True, max_length=160, verbose_name='observação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criada em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta bancária',
                'verbose_name_plural': 'contas bancárias',
                'ordering': ['bank_name', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bankrolltransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='dashboard.bankaccount', verbose_name='conta bancária'),
        ),
    ]
