# Generated by Django 5.2.14 on 2026-06-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_useraccess_id_bankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebet',
            name='extraction_bet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_freebet', to='dashboard.bet', verbose_name='aposta de extração'),
        ),
    ]
