# Generated by Django 5.2.14 on 2026-06-04 13:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_surebet_to_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo inicial'),
        ),
    ]
