# Generated by Django 5.2.14 on 2026-06-09 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_bankaccount_initial_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-BR', 'Português'), ('es', 'Español'), ('en', 'English')], default='pt-BR', max_length=8, verbose_name='idioma')),
                ('currency', models.CharField(choices=[('BRL', 'Real brasileiro'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='BRL', max_length=3, verbose_name='moeda')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'preferência do usuário',
                'verbose_name_plural': 'preferências dos usuários',
            },
        ),
    ]
