# Generated by Django 5.2.14 on 2026-06-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebet',
            name='simple_bet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_freebet', to='dashboard.bet', verbose_name='aposta simples'),
        ),
    ]
