# Generated by Django 5.2.14 on 2026-06-17 05:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_freebet_simple_bet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral')], max_length=20, verbose_name='plano')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('duration_days', models.PositiveIntegerField(verbose_name='dias de acesso')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('provider', models.CharField(default='mercado_pago', max_length=40, verbose_name='gateway')),
                ('provider_preference_id', models.CharField(blank=True, max_length=120, verbose_name='id da preferência')),
                ('provider_payment_id', models.CharField(blank=True, max_length=120, verbose_name='id do pagamento')),
                ('checkout_url', models.URLField(blank=True, verbose_name='url do checkout')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload bruto')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
