# Generated by Django 5.2.14 on 2026-06-20 01:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='odds_boost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='aumento (%)'),
        ),
    ]
