# Generated by Django 5.2.2 on 2026-06-21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0032_bet_settled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField(verbose_name='dias antes do vencimento')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='enviado em')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_reminders', to='dashboard.useraccess', verbose_name='acesso')),
            ],
            options={
                'verbose_name': 'lembrete de assinatura',
                'verbose_name_plural': 'lembretes de assinatura',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionreminder',
            constraint=models.UniqueConstraint(fields=('access', 'days_before'), name='unique_subscription_reminder_per_access_and_day'),
        ),
    ]
