# Generated by Django 5.2.14 on 2026-07-16 03:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_subscriptionreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='freebet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor da freebet'),
        ),
    ]
