# Generated by Django 5.2.14 on 2026-07-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_bet_freebet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='tutorials_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tutoriais vistos em'),
        ),
    ]
